spring.application.name=finsight
jdbc:h2:mem:finsightdb
spring.security.user.name=ravindar
spring.security.user.password=finsight

spring.jpa.hibernate.ddl-auto = update
spring.h2.console.enabled=true